server:
  port: 8002

spring:
  ############### CONEXION A BASE DE DATOS
  datasource:
    url: jdbc:mysql://localhost:3306/socialnetwork
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  ##############################
  